Added support for batch invalidation cronjob
EtherealEngine/ethereal-engine-ops pull request #13
Opened 2024-04-15 18:35 UTC by barankyle

Cronjob will create a single batch invalidation for all routes in a new `invalidation` table. This table is populated from calls to storageProvider.createInvalidation. This prevents CloudFront createInvalidation rate limit errors when many files are replaced/invalidated at once.

2024-04-16 02:24 UTC, hanzlamateen requested changes
Looks good apart from this 1 comment

2024-04-16 02:24 UTC, hanzlamateen commented on etherealengine/values.yaml
> +  hot: pants
What is this value used for?

2024-04-16 17:57 UTC, barankyle commented on etherealengine/values.yaml
> +  hot: pants
A test value, it's been removed.

2024-04-17 07:19 UTC, hanzlamateen approved these changes

2024-04-17 07:19 UTC, merged